// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: proto/anime_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnimeRequest is the Request message to get anime suggestions
type AnimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre          string `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	Limit          int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy         string `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	IncludeRatings bool   `protobuf:"varint,4,opt,name=include_ratings,json=includeRatings,proto3" json:"include_ratings,omitempty"`
	IncludeReviews bool   `protobuf:"varint,5,opt,name=include_reviews,json=includeReviews,proto3" json:"include_reviews,omitempty"`
}

func (x *AnimeRequest) Reset() {
	*x = AnimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_anime_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeRequest) ProtoMessage() {}

func (x *AnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeRequest.ProtoReflect.Descriptor instead.
func (*AnimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_anime_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnimeRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *AnimeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AnimeRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *AnimeRequest) GetIncludeRatings() bool {
	if x != nil {
		return x.IncludeRatings
	}
	return false
}

func (x *AnimeRequest) GetIncludeReviews() bool {
	if x != nil {
		return x.IncludeReviews
	}
	return false
}

// AnimeDetail is the Response message containing anime details
type AnimeDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Genre       string   `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Rating      float32  `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	ReleaseDate string   `protobuf:"bytes,5,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Reviews     []string `protobuf:"bytes,6,rep,name=reviews,proto3" json:"reviews,omitempty"`
}

func (x *AnimeDetail) Reset() {
	*x = AnimeDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_anime_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeDetail) ProtoMessage() {}

func (x *AnimeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeDetail.ProtoReflect.Descriptor instead.
func (*AnimeDetail) Descriptor() ([]byte, []int) {
	return file_proto_anime_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnimeDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnimeDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnimeDetail) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *AnimeDetail) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AnimeDetail) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *AnimeDetail) GetReviews() []string {
	if x != nil {
		return x.Reviews
	}
	return nil
}

// AnimeRespone is the Response message containing a list of anime details
type AnimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeDetails []*AnimeDetail `protobuf:"bytes,1,rep,name=anime_details,json=animeDetails,proto3" json:"anime_details,omitempty"`
}

func (x *AnimeResponse) Reset() {
	*x = AnimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_anime_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeResponse) ProtoMessage() {}

func (x *AnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeResponse.ProtoReflect.Descriptor instead.
func (*AnimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_anime_service_proto_rawDescGZIP(), []int{2}
}

func (x *AnimeResponse) GetAnimeDetails() []*AnimeDetail {
	if x != nil {
		return x.AnimeDetails
	}
	return nil
}

var File_proto_anime_service_proto protoreflect.FileDescriptor

var file_proto_anime_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x63, 0x6c,
	0x75, 0x64, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0e, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x6e, 0x63, 0x6c,
	0x75, 0x64, 0x65, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x0b, 0x41,
	0x6e, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22, 0x48, 0x0a,
	0x0d, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37,
	0x0a, 0x0d, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e,
	0x69, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x61, 0x6e, 0x69, 0x6d, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x32, 0x95, 0x01, 0x0a, 0x0c, 0x41, 0x6e, 0x69, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41,
	0x6e, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x13, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x16, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x13, 0x2e, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x2e, 0x41, 0x6e, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x30, 0x01, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_anime_service_proto_rawDescOnce sync.Once
	file_proto_anime_service_proto_rawDescData = file_proto_anime_service_proto_rawDesc
)

func file_proto_anime_service_proto_rawDescGZIP() []byte {
	file_proto_anime_service_proto_rawDescOnce.Do(func() {
		file_proto_anime_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_anime_service_proto_rawDescData)
	})
	return file_proto_anime_service_proto_rawDescData
}

var file_proto_anime_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_anime_service_proto_goTypes = []any{
	(*AnimeRequest)(nil),  // 0: anime.AnimeRequest
	(*AnimeDetail)(nil),   // 1: anime.AnimeDetail
	(*AnimeResponse)(nil), // 2: anime.AnimeResponse
}
var file_proto_anime_service_proto_depIdxs = []int32{
	1, // 0: anime.AnimeResponse.anime_details:type_name -> anime.AnimeDetail
	0, // 1: anime.AnimeService.GetAnimeSuggestions:input_type -> anime.AnimeRequest
	0, // 2: anime.AnimeService.StreamAnimeSuggestions:input_type -> anime.AnimeRequest
	2, // 3: anime.AnimeService.GetAnimeSuggestions:output_type -> anime.AnimeResponse
	1, // 4: anime.AnimeService.StreamAnimeSuggestions:output_type -> anime.AnimeDetail
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_anime_service_proto_init() }
func file_proto_anime_service_proto_init() {
	if File_proto_anime_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_anime_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AnimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_anime_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AnimeDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_anime_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AnimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_anime_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_anime_service_proto_goTypes,
		DependencyIndexes: file_proto_anime_service_proto_depIdxs,
		MessageInfos:      file_proto_anime_service_proto_msgTypes,
	}.Build()
	File_proto_anime_service_proto = out.File
	file_proto_anime_service_proto_rawDesc = nil
	file_proto_anime_service_proto_goTypes = nil
	file_proto_anime_service_proto_depIdxs = nil
}
